use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: ''
  formats:
    - html
    - json

outgoing:
  request_timeout: 12.0
  proxies:
    http:  http://127.0.0.1:7891
    https: http://127.0.0.1:7891

server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b'

engines:
  - name: wolframalpha
    disabled: false
